# Generated by Django 6.0.3 on 2026-04-25 15:15

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('sector', models.CharField(choices=[('technology', 'Tecnologia'), ('retail', 'Varejo'), ('health', 'Saúde'), ('education', 'Educação'), ('finance', 'Finanças'), ('logistics', 'Logística'), ('construction', 'Construção'), ('other', 'Outro')], max_length=30)),
                ('size', models.CharField(choices=[('micro', 'Até 10 funcionários'), ('small', 'De 11 a 50 funcionários'), ('medium', 'De 51 a 200 funcionários'), ('large', 'De 201 a 1000 funcionários'), ('extra_large', 'Acima de 1000 funcionários')], max_length=15)),
                ('country', models.CharField(max_length=2)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('plan_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativo'), ('inactive', 'Inativo'), ('past_due', 'Pagamento pendente'), ('canceled', 'Cancelado')], default='trial', max_length=20)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
